### PR TITLE
Fix typecast warning

### PR DESCRIPTION
**Pull request by Sampas**

### CODE REVIEW

**Comment by Sampas** [comment]
This fixes a warning in Visual Studio: warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data

**Comment by camgunz** [comment]
Thanks for all your work on CMP so far!

I specifically want that conversion because if it will fit in a float, then we can serialize it as a float.  I'm not aware of a different way to do this, though it's possible there is one.

The typecast changes have been added in different commits, so I'll just close this.  Again thanks :)

**Comment by Sampas** [comment]
Hi again, I think the idea of the conversion is OK but the implementation is just not correct currently. Now it first converts the double to float, and then raises the float to double and saves it to float (warning here), and finally raises the saved float to double and compares it to the original. Whereas in the patched version it converts double to float and then raises the float to double and compares to original to see if it fit.

**Comment by camgunz** [comment]
Oh, yeah.  Why was I being so dense?  I'll merge this tonight, sorry.  And thanks for sticking with it :).

**Comment by Sampas** [comment]
Thanks for getting back to this :) I started to wonder why these were not visible earlier, and found that there's this compiler option that would help: -Wconversion. But it seems the following might also be necessary since there's a lot of errors without this: -Wno-sign-conversion.

**Comment by camgunz** [comment]
@Sampas can make this diff against the develop branch?  I know it's small but I don't want to do it myself and eat yr contribution.  I added those compiler flags so the build will currently fail; once your PR is merged it should clean up again.  I'll close this for now, just make another PR against develop and I'll merge it.

**Pull request closed without merging**
